#include "w:\general\var.h"

extern "C"	void ASM_CALL	CNV_RNormal_Linear(void);
extern "C"	void ASM_CALL	CNV_RStrange_Linear(void);
extern "C"	void ASM_CALL 	CNV_RNormal_Banked(void);
extern "C"	int		CNV_ONormal;

extern "C"	void ASM_CALL	CNV_RGrey(void);
extern "C"	int          	CNV_OGrey;

extern "C"	void ASM_CALL	CNV_R8bitRGB(void);
extern "C"	int             CNV_O8bitRGB;

extern "C"	void ASM_CALL	CNV_RStretch(void);
extern "C"	int             CNV_OStretch;


